name: Rust

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  


env:
  CARGO_TERM_COLOR: always

jobs:
  buildAndRun:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run
      run: cargo run
    - name: Commit README
      run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Update README"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
